### ISSUE TITLE
Do NOT update data manually

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames-rixensart#6]
Hello @vdarmsta,

I see you regularly update manually `data/gender.csv` and `data/other.csv`.
Those 2 are generated by the data process and **MUST** not be updated manually.

They are automatically updated once a month but if you need to update it more often, I've added a button to trigger it here on GitHub.
Go here: https://github.com/EqualStreetNames/equalstreetnames-rixensart/actions/workflows/update-data.yml and click on "Run workflow" button (on branch `master`).

![image](https://user-images.githubusercontent.com/1150563/212466207-6dac2ea3-1bcb-4f59-a916-6739839797b6.png)

Let me know if you have any question!

**Comment by vdarmsta** [comment]
Hi @jbelien ,
Thanks for your mail. 
You ate right, I have regularly manually updated those files (mainly data/gender.csv) recently as I thought it was the right way to proceed.
I really apologize if this is not the case.
I struggled a little bit at beginning to understand how the data was populated to create the map.
I saw that gender.csv was the file for streets named with person having a wikidata page and found out that data.csv could be used for streets named with person not having a wikidata page.
So, for wikidata person, I did update Openstreemap with the wikidata value and thought I had to also update the gender.csv with the wikidata value, but I undersand from your message that the tool is doing it by himself (by just checking the wikidata value on OSM) once a month, right?
Good, so I will not update anymore gender.csv.

Could you let me know what is the purpose of other.csv and if the way I use data.csv is the right way to proceed for streets with a name not on wikidata?

Thank you very much.

**Comment by jbelien** [comment]
> [...] but I undersand from your message that the tool is doing it by himself (by just checking the wikidata value on OSM) once a month, right?

Yes, exactly!
There is an automated data process that will extract all the data from OpenStreetMap and Wikidata once a month (in your case the [1st of the month at 07:00](https://github.com/EqualStreetNames/equalstreetnames-rixensart/actions/runs/3917946649/workflow#L6)).
But sometimes you want to control that update yourself (after having adding a lot of data in OpenStreetMap or Wikidata for instanse) and that's why I added the ["Run workflow" button](https://github.com/EqualStreetNames/equalstreetnames-rixensart/actions/runs/3917946649/workflow#L7) (see initial comment) so if you want to update the data yourself, you just need to click on that button.

> Could you let me know what is the purpose of other.csv [...]

`gender.csv` indeed stores all references to people.
`other.csv` stores all references to everything that's not a person (for instance, in Rixensart "Avenue des Tourterelles").
Even though the goal is to highlight gender, I thought it would also be interesting to display all the data we have even if it's not a person.

![image](https://user-images.githubusercontent.com/1150563/212529653-c3f5a2ce-aa37-4cc5-8864-8527f7bc7b11.png)

> [...] and if the way I use data.csv is the right way to proceed for streets with a name not on wikidata?

That's perfect!
It's of course **always** best to add the data in Wikidata (and OpenStreetMap) but if for some reason that person can't be added to Wikidata (I know sometimes the "validation" rule are a bit strict", it can be added to `data.csv`.


Thanks a lot for all your work!
